### ISSUE TITLE
Bug? Using .AddAutoNumber extension throws a scoping exception (aspnet core 3.1)

### ISSUE THREAD

**Issue by wislon** [0x414c49/AzureAutoNumber#1]
Hi there,

Thanks so much for doing all the heavy lifting with this! 👍 

This is what I have tested it on
* Visual Studio for Windows 16.5.x
* Project is an ASP.NET Core 3.1 Azure Functions (runtime v~3)
* Standard out of the box MS ASP.NET DI framework, no fancy DI containers or anything.

Unfortunately I can't get it to work using the `services.AddAutoNumber()` extension (as described in your blog), it throws the following exception:

```text
[23/04/2020 03:13:24] 
Microsoft.Azure.WebJobs.Script.WebHost: Dependency AutoNumber.Interfaces.IOptimisticDataStore {ReturnDefault} as parameter "optimisticDataStore" reuse CurrentScopeReuse {Lifespan=100} lifespan shorter than its parent's: singleton AutoNumber.UniqueIdGenerator: AutoNumber.Interfaces.IUniqueIdGenerator {ReturnDefault}
[23/04/2020 03:13:24]   from ambiently scoped container with {no name, Parent={no name, Parent={no name}}}
[23/04/2020 03:13:24] To turn Off this error, specify the rule with new Container(rules => rules.WithoutThrowIfDependencyHasShorterReuseLifespan()).
```

It appears as tho making a singleton rely on an (effectively transient) dependency makes it barf. Perhaps it's aspnet core 3.x, I'm not sure, but the error does make sense. Here's a link which describes roughly what it is going on, in case other people are having a problem with it too:

https://medium.com/@pugillum/the-azure-function-connection-limit-with-dependency-injection-c52982199cf1

and 

https://blog.markvincze.com/two-gotchas-with-scoped-and-singleton-dependencies-in-asp-net-core/

I was able to resolve it by manually building the dependency chain (I just made everything singletons because that's what suits my purpose for my solution, but ymmv). It looks pretty much like this now:

```csharp
// earlier on in another part of town (I had to fully qualify it coz
// I am using other Azure Storage libs)
using MWAS = Microsoft.WindowsAzure.Storage;

...

// set up the DI chain for the auto-incrementing numeric-code generation.
// it needs a CloudStorageAccount pre-registered with DI,
// has to be the MS.WindowsAzure.Storage.blah type tho, or it won't work

services.AddSingleton<MWAS.CloudStorageAccount, MWAS.CloudStorageAccount> ((svcs) =>
{
    var config = svcs.GetService<IConfiguration>();
    var connectionString = config[BlobStorageConstants.BlobStorageConnectionString];
    var cloudStorageCount = MWAS.CloudStorageAccount.Parse(connectionString);
    return cloudStorageCount;
});

services.AddOptions<AutoNumberOptions>().Configure<IConfiguration>
(
    (settings, configuration) =>
    {
        configuration.GetSection("AutoNumber").Bind((object) settings);
    }
);

// this makes it barf too, so I switched to using a singleton, below
//services.AddScoped<IOptimisticDataStore, BlobOptimisticDataStore>();
services.AddSingleton<IOptimisticDataStore, BlobOptimisticDataStore>(x =>
{
    var autoNumberOptions = x.GetService<IOptions<AutoNumberOptions>>();
    var storageAccount = x.GetService<MWAS.CloudStorageAccount>();
    var optimisticBlobStore = new BlobOptimisticDataStore(storageAccount, autoNumberOptions);
    return optimisticBlobStore;
});

services.AddSingleton<IUniqueIdGenerator, UniqueIdGenerator>(x =>
{
    var optimisticStore = x.GetService<IOptimisticDataStore>();
    var uniqueIdGenerator = new UniqueIdGenerator(optimisticStore);
    return uniqueIdGenerator;
});

```

It's a bit more complex, because I kind of had to force it to use specific constructors for all the entities, but the end result works perfectly. So, thanks again for building and publishing this! 👍

**Comment by 0x414c49** [comment]
@wislon  Such a detailed issue. I really appreciate that. I will take a look and see what else we can do about it. 

> It's a bit more complex, because I kind of had to force it to use specific constructors for all the entities, but the end result works perfectly. So, thanks again for building and publishing this! 👍


Honestly, I just ported the library to .NET Core and updated everything. All credits go to the  Tatham Oddie.

**Comment by wislon** [comment]
Cheers @0x414c49, no problem, happy to help :). There's not much worse than coming across a problem like this and knowing there must be a way to solve it, but literally not having the time to do so. So hopefully my 'solution' (such as it is) can help someone else, even if it's copypasta and some renaming ;) .

I suspect that if you just set the `IOptimisticDataStore` and `CloudStorageAccount` deps to be singletons as well, then that'll be fine for most peoples' cases; it's not like they're massive resource pigs. I guess the gatekeeper over the whole thing is the aspnet core DI framework itself, so we don't get much say in it... and I was reluctant to set up the container to allow it to turn the error message off (as suggested in the exception).

**Comment by 0x414c49** [comment]
I'm now investing some-time on the project and I think you are totally correct about making `BlobOptimisticDataStore` singleton. It's a dependency of `UniqueIdGenerator` (which is already singleton) so that doesn't make sense to make `BlobOptimisticDataStore`  Scoped.

I'm gonna make some changes on the DI part, especially provide more generic ways to add this project to the IoC.

**Comment by 0x414c49** [comment]
@wislon I fixed this issue and created an options builder during registering the service. Can you check the PR here #2?
