### ISSUE TITLE
AzureAutoNumber uses a deprecated package

### ISSUE THREAD

**Issue by ilmax** [0x414c49/AzureAutoNumber#18]
Hey @0x414c49 , thank you for this package. I realized it's using a deprecated nuget package to talk to the azure storage, do you have any plans to update this? Will you eventually accept a PR?

Thank you

**Comment by 0x414c49** [comment]
Hello, I had a plan to use the new packages but didn’t find enough time to work on it. Yea, I accept PRs

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Massimiliano Donini ***@***.***>
Sent: Thursday, August 4, 2022 2:52:55 PM
To: 0x414c49/AzureAutoNumber ***@***.***>
Cc: Ali Bahrami ***@***.***>; Mention ***@***.***>
Subject: [0x414c49/AzureAutoNumber] AzureAutoNumber uses a deprecated package (Issue #18)


Hey @0x414c49<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F0x414c49&data=05%7C01%7C%7C812690ac7cc64243e61f08da76184079%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637952143775686754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NpMekdmuZDr4O%2FH8T5%2FcyHAD5AMotrIn1uHhvRY11vc%3D&reserved=0> , thank you for this package. I realized it's using a deprecated nuget package to talk to the azure storage, do you have any plans to update this? Will you eventually accept a PR?

Thank you

**Comment by ilmax** [comment]
Hello @0x414c49, did you had any chance to look into #19?

**Comment by ilmax** [comment]
@0x414c49 friendly ping :) Did you had time to look into the PR?
