### ISSUE TITLE
Dependency Injection how to implemented

### ISSUE THREAD

**Issue by princeantony1073** [0x414c49/AzureAutoNumber#8]
After added Package from nugget, I m not able to run the Azure Functions, getting error as Dependency Injection. How to resolve this DJ?

**Comment by 0x414c49** [comment]
Hi @princeantony1073 ,

- What version of the Package you're using?
- Could you give me more information?
- Or a simple project of your Azure Functions?

**Comment by princeantony1073** [comment]
Azure functions which will connect cosmos db. Instead of generating GUID as id, I want to generate AutoSequence number.
So i tired to use this package. After Installed and running project i m getting below error.

![image](https://user-images.githubusercontent.com/66243387/105494184-6b721380-5ce0-11eb-99aa-3fc63233065c.png)

![image](https://user-images.githubusercontent.com/66243387/105494333-a411ed00-5ce0-11eb-8993-678d303947c0.png)

![image](https://user-images.githubusercontent.com/66243387/105496285-49c65b80-5ce3-11eb-85ca-d61420a823a3.png)

**Comment by 0x414c49** [comment]
Now I understand. You need to define the dependencies inside the `Configure` method. If you are new to DependencyInjection for AzureFunctions feel free and read my article [here](https://itnext.io/inversion-of-control-ioc-in-azure-functions-110393662c61?source=friends_link&sk=5ca1d2e848a44a7b98a5263d9ce94bb9):

but if you are familiar just add dependencies like example:

```
builder.services.AddAutoNumber(Configuration, x =>
{
	return x.UseContainerName("container-name")
	 .UseStorageAccount("connection-string-or-connection-string-name")
   //.UseStorageAccount(cloudStorageAccountInstance)
	 .SetBatchSize(10)
	 .SetMaxWriteAttempts(100)
	 .Options;
});
```

**Comment by princeantony1073** [comment]
Thanks for the update, Configuration which value to be passed.

**Comment by 0x414c49** [comment]
You're welcome. Is that a question? " Configuration which value to be passed. "

**Comment by princeantony1073** [comment]
yes, which value to be passed for that value

**Comment by 0x414c49** [comment]
I don't get your question, but configure it as below:

Make a storage account and get its connection string, then in the code below replace your connection string:

```
builder.services.AddAutoNumber(Configuration, x =>
{
	return x.UseContainerName("seq-numbers")
	 .UseStorageAccount("storageAccountConnectionString")
   //.UseStorageAccount(cloudStorageAccountInstance)
	 .SetBatchSize(10)
	 .SetMaxWriteAttempts(100)
	 .Options;
});
```
